import type { Influencer } from "./types"

export const influencers: Influencer[] = [
  {
    id: "1",
    date: "22/01/2025 11:54",
    name: "Alvxaro",
    nickname: "alvxaro",
    rate: 2.0,
    when_worked: "2024",
    work_description:
      "Terrível... Não trabalha com o que foi combinado! Some não dar satisfação, não entrega! Parece q a marca está fazendo um favor para ele em pagar muitoooo caro pra fazer o básico de um influenciador! Não respeita a equipe! Porem tem números!",
    advice_description: "Não espere datas cumpridas...",
    sentiment: "negative",
    sentiment_score: 0.97438,
    final_rating: 0.19795,
  },
  {
    id: "2",
    date: "23/01/2025 12:00",
    name: "Maria Silva",
    nickname: "mariasilva",
    rate: 4.5,
    when_worked: "2024",
    work_description: "Excelente profissional, entrega sempre no prazo e com qualidade.",
    advice_description: "Ótima para parcerias de longo prazo.",
    sentiment: "positive",
    sentiment_score: 0.95,
    final_rating: 0.85,
  },
  {
    id: "3",
    date: "24/01/2025 13:30",
    name: "João Santos",
    nickname: "joaosantos",
    rate: 3.8,
    when_worked: "2024",
    work_description: "Bom trabalho, mas às vezes atrasa nas entregas.",
    advice_description: "Acompanhar de perto os prazos.",
    sentiment: "neutral",
    sentiment_score: 0.6,
    final_rating: 0.7,
  },
  {
    id: "4",
    date: "25/01/2025 10:00",
    name: "Ana Oliveira",
    nickname: "anaoliveira",
    rate: 4.8,
    when_worked: "2024",
    work_description: "Profissional excepcional, sempre supera as expectativas.",
    advice_description: "Excelente para campanhas de alto impacto.",
    sentiment: "positive",
    sentiment_score: 0.98,
    final_rating: 0.92,
  },
  {
    id: "5",
    date: "26/01/2025 14:45",
    name: "Carlos Ferreira",
    nickname: "carlosferreira",
    rate: 3.5,
    when_worked: "2024",
    work_description: "Desempenho mediano, precisa melhorar a comunicação.",
    advice_description: "Estabelecer check-ins regulares.",
    sentiment: "neutral",
    sentiment_score: 0.5,
    final_rating: 0.6,
  },
  {
    id: "6",
    date: "27/01/2025 09:15",
    name: "Luísa Mendes",
    nickname: "luisamendes",
    rate: 4.2,
    when_worked: "2024",
    work_description: "Criativa e engajada, traz resultados consistentes.",
    advice_description: "Ótima para campanhas inovadoras.",
    sentiment: "positive",
    sentiment_score: 0.85,
    final_rating: 0.8,
  },
  {
    id: "7",
    date: "28/01/2025 16:20",
    name: "Ricardo Alves",
    nickname: "ricardoalves",
    rate: 3.9,
    when_worked: "2024",
    work_description: "Bom relacionamento com a audiência, mas precisa melhorar a pontualidade.",
    advice_description: "Definir prazos claros no início dos projetos.",
    sentiment: "neutral",
    sentiment_score: 0.7,
    final_rating: 0.75,
  },
]

